#
###################################
# Site wide configuration
####################################
#
title: about
email: 
description: 
url: https://skrish13.github.io # the base hostname & protocol for your site
keywords: []

#
###################################
# Jekyll configuration
####################################
#
timezone:          IST
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Krish
  avatar: 
  job: ""
  bio: "More of a space to put out ideas and information. Read at your own risk."
  email: skrish at protonmail dot ch
  disqus-shortname: https-skrish13-github-io
  twitter: skrish_13 #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: skrish13 #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
